<?php

return [
    'subjects' => [
        \App\Models\User::class => 'المستخدم',
        \App\Models\Car::class  => 'السيارة',
        \App\Models\Role::class  => 'الدور',
        \App\Models\Tip::class  => 'الترب',
        \App\Models\Container::class => 'الحاوية',
        \App\Models\DailyTransaction::class => 'المعاملة اليومية',
        \App\Models\CustomsDeclaration::class => 'البيانات الجمركية',
        \App\Models\CarChangeOilData::class => 'بيانات تغيير الزيت',
        \App\Models\SellAndBuy::class => 'البيع والشراء',
        \App\Models\Flatbed::class => 'سطحات',
        \App\Models\FlatbedContainer::class => 'حاويات السطحات',
        // زد ما تشاء...
    ],

    'subjects_aliases' => [
        'user'                => 'المستخدم',
        'car'                 => 'السيارة',
        'role'                => 'الدور',
        'tip'                 => 'النصيحة',
        'container'           => 'الحاوية',
        'dailytransaction'    => 'المعاملة اليومية',
        'carchangeoildata'    => 'تغيير الزيت',
        'sellandbuy'          => 'البيع والشراء',
        'flatbed'             => 'سطحة',
        'flatbedcontainer'    => 'حاوية السطحة',
    ],

    'fields' => [
        'name'                => 'الاسم',
        'email'               => 'البريد',
        'avatar'              => 'الصورة',
        'id'                  => 'المعرف',
        'password'            => 'كلمة المرور',
        'driver_id'           => 'معرف السائق',
        'number'              => 'رقم اللوحة',
        'odometer'            => 'عداد السيارة',
        'oil_change_number'   => 'كيلومترات بين تغييرات الزيت',
        'description'         => 'الوصف',
        'amount'              => 'المبلغ',
        'status'              => 'الحالة',
        'auditable_type'      => 'نوع الموديل',
        'event'               => 'الحدث',
        'price'               => 'السعر',
        'statement_number'    => 'رقم البيان',
        'size'                => 'الحجم',
        'weight'              => 'الوزن',
        'container_id'        => 'معرف الحاوية',
        'customs_id'         => 'معرف الجمارك',
        'car_id'             => 'معرف السيارة',
        'clearance_office_id' => 'معرف مكتب التخليص',
        'client_id'          => 'معرف العميل',
        'expire_date'       => 'تاريخ الانتهاء',
        'statement_status'   => 'حالة البيان',
        'is_rent'            => 'هل هو إيجار',
        'phone'              => 'رقم الهاتف',
        'operational_number' => 'رقم التشغيل',
        'is_active'          => 'هل هو نشط',
        'role_id'            => 'معرف الدور',
        'permissions'       => 'الصلاحيات',
        'updated_at'          => 'آخر تحديث',
        'created_at'          => 'تاريخ الإنشاء',
        // أضف باقي الحقول الشائعة عندك
    ],
];
